apiVersion: v1
kind: Service
metadata:
  name: container-service
  labels:
    app: micro-frontends
spec:
  type: NodePort
  ports:
    - port: 9000
      name: http
      nodePort: 30000
  selector:
    app: micro-frontends
